trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'
  appLocation: '.'
  outputLocation: 'dist/bookealowebapp.client'
  azureStaticWebAppName: 'bookealo-frontend'
  azureSubscription: 'bookealo-connection'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'Build Angular App'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(appLocation)'
    output_location: '$(outputLocation)'
    azure_static_web_apps_api_token: $(deployment_token)
  displayName: 'Deploy to Azure Static Web App'
